version: 2
builds:
  - binary: askcloudhelloworld
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

homebrew_casks:
  - name: cli-mate
    homepage: "https://github.com/yuldoshevgg/cli-mate"
    repository:
      owner: yuldoshevgg             
      name: homebrew-cli-tools 
    commit_author: 
      name: yuldoshevgg
      email: yuldoshevgg@gmail.com
    
checksum:
  name_template: 'checksums.txt'