builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  prerelease: true

univeral_binaries:
  - replace: true

brews:
  - name: cli-mate
    homepage: "https://github.com/yuldoshevgg/cli-mate"
    tap:
      owner: yuldoshevgg             
      name: homebrew-cli-tools 
    commit_author: 
      name: yuldoshevgg
      email: yuldoshevgg@gmail.com
    
checksums:
  name_template: 'checksums.txt'
